export const MAKE_OUT_MAIN_FEATURED_POST_SUCCESS = 'MAKE_OUT_MAIN_FEATURED_POST_SUCCESS';
export const MAKE_OUT_MAIN_FEATURED_POST_FAILURE = 'MAKE_OUT_MAIN_FEATURED_POST_FAILURE';
export const UPDATE_NOTIFY = 'UPDATE_NOTIFY';
export const EMPTY_NOTIFY = 'EMPTY_NOTIFY';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
